name: Ping Render App

on:
  schedule:
    - cron: '*/10 * * * *'  # Every 10 minutes
  workflow_dispatch:       # Allows manual runs too

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Curl your Render app
        run: |
          curl -s -o /dev/null -w "%{http_code}" https://carlosmurga.onrender.com
